server:
  port: 8888 # ??????????? ???? ??? ??????-???????
spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: git # ????????? ??? ???????? ???????? ? ???-???? (? ??. ?????????? ????? ???)
  cloud:
    config:
      server:
        git:
          uri:

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # ???? ? ??????? (? ??. ?????????? ???)

